prefix: "§f§l[§bLengbanlist§f§l]" #插件前缀
sendtime: 5 #以分钟为单位
opensendtime: true #开启循环播报封禁人数
Model: "Default" #当前模型
valid-models: "Default English HuTao Furina Zhongli Keqing Xiao Ayaka Zero Herta" #可用模型
#以下建议只选一个开启
update-check: false # 是否启用更新检查（默认：false）
auto-update: false # 是否启用自动更新（默认：false）

#数据库  （尚未实现）
database: 
  type: "yml"  # 或 "mysql"
  mysql:
    host: "localhost"
    port: 3306
    database: "lengbanlist"
    username: "root"
    password: "password"
    
    
